version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "daily"
      time: "02:00"
    commit-message:
      prefix: "maint"
      include: scope
    labels: [ ]

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    commit-message:
      prefix: "maint"
      include: scope
    labels: [ ]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "daily"
      time: "02:00"
    commit-message:
      prefix: "maint"
      include: scope
    labels: [ ]
