version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - communityid
  - coobaha
  - devcontainer
  - Eventiva
  - fastify
  - joggr
  - learnbit
  - leasot
  - pino
  - resourcetypes
  - serverid
  - todos
  - zmodel
  - zoomable
ignoreWords: []
import: []
enableFiletypes:
  - dockercompose
  - dockerfile
  - toml
  - zmodel
language: en,en-GB
