###
# @format
# -----
# Project: @eventiva/eventiva
# File: dockerfile
# Path: \.devcontainer\dockerfile
# Created Date: Wednesday, November 22nd 2023
# Author: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
# -----
# Contributing: Please read through our contributing guidelines. Included are directions for opening
# issues, coding standards, and notes on development. These can be found at https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
# 
# Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
# welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
# -----
# Copyright (c) 2023 Eventiva - All Rights Reserved
# LICENSE: Creative Commons Zero v1.0 Universal (CC0-1.0)
# -----
# This program has been provided under confidence of the copyright holder and is 
# licensed for copying, distribution and modification under the terms of
# the Creative Commons Zero v1.0 Universal (CC0-1.0) published as the License,
# or (at your option) any later version of this license.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Creative Commons Zero v1.0 Universal for more details.
# 
# You should have received a copy of the Creative Commons Zero v1.0 Universal
# along with this program. If not, please write to: jonathan.stevens@eventiva.co.uk,
# or see https://creativecommons.org/publicdomain/zero/1.0/legalcode
# 
# DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
# -----
# Last Modified: 22-11-2023
# By: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
# Current Version: 0.0.0
###

FROM frappe/erpnext:v15.2.0 AS base

WORKDIR /home/frappe/frappe-bench/
# check to see if the lms folder already exists and if it doesn't then clone the repo
RUN if [ ! -d "/home/frappe/frappe-bench/apps/lms" ] ; then bench get-app https://github.com/frappe/lms.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/lending" ] ; then bench get-app https://github.com/frappe/lending.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/healthcare" ] ; then bench get-app https://github.com/frappe/health.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/payments" ] ; then bench get-app https://github.com/frappe/payments.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/webshop" ] ; then bench get-app https://github.com/frappe/webshop.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/it_management" ] ; then bench get-app https://github.com/phamos-eu/it_management.git ; fi

RUN if [ ! -d "/home/frappe/frappe-bench/apps/eventiva_core" ] ; then bench get-app https://github.com/Eventiva/eventiva_core.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/vetting" ] ; then bench get-app https://github.com/eventiva/vetting.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/fleet_management" ] ; then bench get-app https://github.com/eventiva/fleet_management.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/gaming" ] ; then bench get-app https://github.com/eventiva/gaming.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/custody" ] ; then bench get-app https://github.com/eventiva/custody.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/justice" ] ; then bench get-app https://github.com/eventiva/justice.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/incident_management" ] ; then bench get-app https://github.com/eventiva/incident_management.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/teamspeak_integration" ] ; then bench get-app https://github.com/eventiva/Teamspeak-Integration.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/discord_integration" ] ; then bench get-app https://github.com/eventiva/discord_integration.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/control_centre" ] ; then bench get-app https://github.com/eventiva/Control-Centre.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/grand_theft_auto" ] ; then bench get-app https://github.com/eventiva/grand_theft_auto.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/segment_connect" ] ; then bench get-app https://github.com/eventiva/Segment_Connect.git ; fi

# installl bit via bvm using npx @teambit/bvm install
RUN npx @teambit/bvm install

# install opencommit via npm globally
RUN npm install -g opencommit

