packages:
    - 'packages/core'
    - 'packages/databases/*'
    - 'packages/cluster-tooling'
    - 'packages/test-repo'
    - 'packages/extensions/*'
    - 'packages/integrations/*'
    - 'packages/platforms/*'
