/**
 * Contact entity types and definitions.
 * This file declares the Drizzle columns and TypeScript types for the dynamic Contact entity.
 * The actual entity instance is generated by Core during Phase 2 of startup.
 *
 * Registry columns must be Drizzle column builders, not a built `pgTable` result — finalization
 * merges builders into `buildTableInternal`; built columns lack `.setName` and throw.
 *
 * Do not add `createdBy` / `createdAt` / etc. here: `buildTableInternal` adds them. `created_by` FK targets
 * `contact.id` (self-reference when contact is the configured creator table). Relations live in `workflow.ts`.
 */
import { Base, type EntityRpc } from '@eventiva/core';
import { createInsertSchema, createSelectSchema, defineExtensionTable } from '@eventiva/databases.pg';
import * as Schema from 'effect/Schema';

const { registryColumns: contactRegistryColumns, schemaTable: contactColumns } = defineExtensionTable(
    'contact',
    (c) => ({
        id: c.typeid('id', { type: 'contact' }),
        firstname: c.text('firstname').notNull(),
        lastname: c.text('lastname').notNull(),
        dateOfBirth: c.date('date_of_birth', { mode: 'string' }).notNull(),
        email: c.text('email').notNull(),
        phone: c.text('phone'),
    })
);

export { contactColumns, contactRegistryColumns };
const ContactSchema = createSelectSchema(contactColumns);
/** Server assigns `id` via `genId`; omit from HTTP/RPC create body (insert schema requires PK after typeid.primaryKey()). */
const ContactCreatePayloadSchema = createInsertSchema(contactColumns).pipe(Schema.omit('id'));

/**
 * Contact entity class: CRUD + cluster entity. Export as value so the platform can
 * register it with the cluster (ContactEntity.layer) and expose it in entity endpoints.
 */
export class ContactEntity extends Base<ContactEntity>()('Contact', ContactSchema, {
    tableName: 'contact',
    withDelete: true,
    createPayloadSchema: ContactCreatePayloadSchema,
}) {}

// Augment the global registry so that `EntityRegistry.get("Contact")` returns the correct type.
declare module '@eventiva/core' {
    export interface RegisteredEntities {
        Contact: typeof ContactEntity;
    }
}

/** Entity ID for the shared contact entity. Use when calling Contact.client("store"). */
export const CONTACT_ENTITY_ID = 'store';

// Export types to be used throughout the extension
export type Contact = typeof ContactEntity;
export type ContactRpc = EntityRpc<typeof ContactEntity.entity>;
export type ContactRecord = Schema.Schema.Type<typeof ContactEntity>;
