/**
 * Contact entity types and definitions.
 * This file declares the Drizzle columns and TypeScript types for the dynamic Contact entity.
 * The actual entity instance is generated by Core during Phase 2 of startup.
 */
import { pgTable, text, date } from "drizzle-orm/pg-core"
import { createSelectSchema } from "drizzle-orm/effect-schema"
import { Base, type EntityRpc } from "@eventiva/core"
import * as Schema from "effect/Schema"
import { typeid } from "@eventiva/databases.pg"

export const contactColumns = {
  id: typeid("id", { type: "contact" }),
  fullname: text("fullname").notNull(),
  dateOfBirth: date("date_of_birth").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull()
}

// Dummy table to extract the generic schema type for TypeScript (uses text for id to avoid type conflicts)
const dummyTable = pgTable("contact", {
  id: text("id"),
  fullname: text("fullname").notNull(),
  dateOfBirth: date("date_of_birth").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull()
})
const ContactSchema = createSelectSchema(dummyTable)

// Dummy class for type extraction
class ContactType extends Base<ContactType>()("Contact", ContactSchema, { withDelete: true }) {}

// Augment the global registry so that `EntityRegistry.get("Contact")` returns the correct type.
declare module "@eventiva/core" {
  export interface RegisteredEntities {
    Contact: typeof ContactType
  }
}

/** Entity ID for the shared contact entity. Use when calling Contact.client("store"). */
export const CONTACT_ENTITY_ID = "store"

// Export types to be used throughout the extension
export type Contact = typeof ContactType
export type ContactRpc = EntityRpc<typeof ContactType.entity>
export type ContactRecord = Schema.Schema.Type<typeof ContactType>
