name: Trunk Check setup
description: Set up dependencies for Trunk Check

runs:
  using: composite
  steps:
  - id: Initialize Bit
    shell: bash
    run: ../../scripts/bit-init.sh
  - id: Verify and Build Bit
    shell: bash
    run: ../../scripts/verify.sh
