###
 # @format
 # -----
 # Project: @eventiva/eventiva
 # File: 2-bug_report.yml
 # Path: \.github\ISSUE_TEMPLATE\2-bug_report.yml
 # Created Date: Monday, April 17th 2023
 # Author: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
 # -----
 # Contributing: Please read through our contributing guidelines. Included are directions for opening
 # issues, coding standards, and notes on development. These can be found at https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
 # 
 # Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
 # welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
 # -----
 # Copyright (c) 2023 Eventiva - All Rights Reserved
 # LICENSE: GNU General Public License v3.0 only (GPL-3.0)
 # -----
 # This program has been provided under confidence of the copyright holder and is 
 # licensed for copying, distribution and modification under the terms of
 # the GNU General Public License v3.0 only (GPL-3.0) published as the License,
 # or (at your option) any later version of this license.
 # 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # Creative Commons Zero v1.0 Universal for more details.
 # 
 # You should have received a copy of the GNU General Public License v3.0 only
 # along with this program. If not, please write to: jonathan.stevens@eventiva.co.uk,
 # or see https://www.gnu.org/licenses/gpl-3.0-standalone.html
 # 
 # DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
 # -----
 # Last Modified: 12-12-2023
 # By: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
 # Current Version: 0.0.0
 ###

name: Report a issue
description: Create a report to help us improve
title: "bug([context]): "
labels: ["Sweep"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report, we greatly appriciate it! 
  - type: markdown
    attributes:
      value: |
        Please use [context] in title to describe the folder path which related to this issue.
        Context example: docs(projects/modules/eventiva_core): {your title here}
  - type: dropdown
    attributes:
      label: Features
      description: What product or feature(s) affected?
      multiple: true
      options:
        - "Bots - Discord - Client"
        - "Bots - Discord - Tickets"
        - "Bots - Discord - Helper"
        - "Framework - Frappe"
        - "Modules - Control Center"
        - "Modules - Custody"
        - "Modules - Discord Intergration"
        - "Modules - Eventiva Core"
        - "Modules - Fleet Management"
        - "Modules - Gaming"
        - "Modules - Incident Management"
        - "Modules - Justice"
        - "Modules - Segment Connect"
        - "Modules - Teamspeak Integration"
        - "Modules - Vetting & Screening"
        - "Modules - ERPNext"
        - "Modules - Human Resources"
        - "Modules - Website Builder"
        - "Modules - IT Management"
        - "Modules - Webshop"
        - "Modules - Payments"
        - "Modules - Healthcare"
        - "Modules - Lending"
        - "Modules - Learning Management System"
        - "Workflows - .github"
        - "Workflows - Awesome Frappe"
        - "Workflows - Change Report"
        - "Workflows - Environments - Discord - Bot"
        - "Workflows - Generators - Discord - Bot"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Console Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

  - type: input
    attributes:
      label: Platform
      description: e.g. macOS, Google Cloud, ubuntu 18.04
    validations:
      required: true
  - type: input
    attributes:
      label: Browser
      description: e.g. Safari, chrome, edge, firefox
  - type: input
    attributes:
      label: Node Version
      description: e.g. v16.8.0
  - type: input
    attributes:
      label: Yarn Version
      description: e.g. v1.22.4
  - type: input
    attributes:
      label: Docker Version
      description: e.g. 19.03.12, build 48a66213fe

  - type: markdown
    attributes:
      value: |
        Please be honest here, we don't mind if you haven't done all these steps; 
        however, we need to know where has been tested and how extensively we need to test it ourselves.

        We would appreciate it if you could maintain this section cleanly and clearly.
  - type: checkboxes
    attributes:
      label: issue Checklist
      options:
        - label: I have reproduced on my application version
          required: false
        - label: I have reproduced on a clean installation
          required: false
        - label: I have reproduced on a development build
          required: false
        - label: I have included logs or screenshots
          required: false
        - label: I have contacted support via the official website
          required: false
        - label: I have asked the community for guidance
          required: false
        - label: I have linked any related issues
          required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description:
        The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/Eventiva/contributors/blob/main/CODE_OF_CONDUCT.md)
          required: true
