###
 # @format
 # -----
 # Project: @eventiva/eventiva
 # File: 4-doc_review.yml
 # Path: \.github\ISSUE_TEMPLATE\4-doc_review.yml
 # Created Date: Monday, April 17th 2023
 # Author: Jonathan Stevens (Email: jonathan@Eventiva.co.uk, Github: https://github.com/TGTGamer)
 # -----
 # Contributing: Please read through our contributing guidelines. Included are directions for opening
 # issues, coding standards, and notes on development. These can be found at https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
 # 
 # Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
 # welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
 # -----
 # Copyright (c) 2023 Eventiva - All Rights Reserved
 # LICENSE: GNU General Public License v3.0 only (GPL-3.0)
 # -----
 # This program has been provided under confidence of the copyright holder and is 
 # licensed for copying, distribution and modification under the terms of
 # the GNU General Public License v3.0 only (GPL-3.0) published as the License,
 # or (at your option) any later version of this license.
 # 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # Creative Commons Zero v1.0 Universal for more details.
 # 
 # You should have received a copy of the GNU General Public License v3.0 only
 # along with this program. If not, please write to: jonathan@Eventiva.co.uk,
 # or see https://www.gnu.org/licenses/gpl-3.0-standalone.html
 # 
 # DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
 # -----
 # Last Modified: 11-12-2023
 # By: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
 # Current Version: 0.0.0
 ###


name: Documentation review
description: A review to highlight issues in documentation
title: "docs([context]): "
labels: ["Sweep"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this review, we greatly appriciate it!
  - type: markdown
    attributes:
      value: |
        Please use [context] in title to describe the folder path which related to this issue.
        Context example: docs(projects/modules/eventiva_core): {your title here}
  - type: dropdown
    attributes:
      label: Features
      description: What product or feature(s) affected?
      multiple: true
      options:
        - "Bots - Discord - Client"
        - "Bots - Discord - Tickets"
        - "Bots - Discord - Helper"
        - "Framework - Frappe"
        - "Modules - Control Center"
        - "Modules - Custody"
        - "Modules - Discord Intergration"
        - "Modules - Eventiva Core"
        - "Modules - Fleet Management"
        - "Modules - Gaming"
        - "Modules - Incident Management"
        - "Modules - Justice"
        - "Modules - Segment Connect"
        - "Modules - Teamspeak Integration"
        - "Modules - Vetting & Screening"
        - "Modules - ERPNext"
        - "Modules - Human Resources"
        - "Modules - Website Builder"
        - "Modules - IT Management"
        - "Modules - Webshop"
        - "Modules - Payments"
        - "Modules - Healthcare"
        - "Modules - Lending"
        - "Modules - Learning Management System"
        - "Workflows - .github"
        - "Workflows - Awesome Frappe"
        - "Workflows - Change Report"
        - "Workflows - Environments - Discord - Bot"
        - "Workflows - Generators - Discord - Bot"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Path
      description: What docs or doc section involved? Include links or paths.
      placeholder: "projects/website/readme.md"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Problem
      description: What type of issue have you identified?
      multiple: false
      options:
        - "Problem with a specific document"
        - "Feature/process that's not addressed sufficiently"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Cases
      description: |
        What audience is it intended?
        What roles and scenarios?
        Include use cases, benefits, and/or goals for this work.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solutions
      description: What could we add to make solve this issue? Any concepts, procedures, reference info we could add.
    validations:
      required: true
  - type: textarea
    attributes:
      label: References
      description: Where did this first appear (if known) and has any other issues been opened related to this?
      value: |
        Related Pull Request(s):
        Related issue(s):
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description:
        The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/Eventiva/contributors/blob/develop/CODE_OF_CONDUCT.md)
          required: true
