###
 # @format
 # -----
 # Project: @eventiva/eventiva
 # File: doc_review.yml
 # Path: \.github\ISSUE_TEMPLATE\doc_review.yml
 # Created Date: Monday, April 17th 2023
 # Author: Jonathan Stevens (Email: jonathan@Eventiva.co.uk, Github: https://github.com/TGTGamer)
 # -----
 # Contributing: Please read through our contributing guidelines. Included are directions for opening
 # issues, coding standards, and notes on development. These can be found at https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
 # 
 # Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
 # welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
 # -----
 # Copyright (c) 2023 Eventiva - All Rights Reserved
 # LICENSE: Creative Commons Zero v1.0 Universal (CC0-1.0)
 # -----
 # This program has been provided under confidence of the copyright holder and is 
 # licensed for copying, distribution and modification under the terms of
 # the Creative Commons Zero v1.0 Universal (CC0-1.0) published as the License,
 # or (at your option) any later version of this license.
 # 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # Creative Commons Zero v1.0 Universal for more details.
 # 
 # You should have received a copy of the Creative Commons Zero v1.0 Universal
 # along with this program. If not, please write to: jonathan@Eventiva.co.uk,
 # or see https://creativecommons.org/publicdomain/zero/1.0/legalcode
 # 
 # DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
 # -----
 # Last Modified: 08-05-2023
 # By: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
 # Current Version: 0.0.0
 ###


name: Documentation review
description: A review to highlight issues in documentation
title: "docs([context]): "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this review, we greatly appriciate it!
  - type: markdown
    attributes: 
      value: |
        Please use [context] in title to describe the part of the mono-repo is related to this issue.
        Context example: docs(components): {your title here}
        Valid options are: 
          - directory: The frontend website which displays our directory systems
          - proxy: The api endpoint for proxied connections to private ERP instances
          - image: The build image used when creating private ERP instances 
          - terraform: The definition of our build processes
          - ci/cd: The automations which run at issue create, pull request or push
          - cli: The custom rush based cli, used to streamline development processes
          - erp: The default module within our ERP instances
          - frappe: The frappe ecosystem which our erp instances are built on
          - payments: The payments module within our ERP instances
          - tours: The tours module within our ERP instances
          - logistics: The logistics module within our ERP instances
          - banking: The banking module within our ERP instances
          - tickets: The tickets module within our ERP instances
          - marketing: The marketing module within our ERP instances
          - hospitality: The hospitality module within our ERP instances
  - type: dropdown
    attributes:
      label: Features
      description: What product or feature(s) affected?
      multiple: true
      options:
        - "directory"
        - "proxy"
        - "image"
        - "terraform"
        - "ci/cd"
        - "cli"
        - "erp"
        - "frappe"
        - "payments"
        - "tours"
        - "logistics"
        - "banking"
        - "tickets"
        - "marketing"
        - "hospitality"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Path
      description: What docs or doc section involved? Include links or paths.
      placeholder: "projects/website/readme.md"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Problem
      description: What type of issue have you identified?
      multiple: false
      options:
        - "Problem with a specific document"
        - "Feature/process that's not addressed sufficiently"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Cases
      description: |
        What audience is it intended?
        What roles and scenarios?
        Include use cases, benefits, and/or goals for this work.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Solutions
      description: What could we add to make solve this issue? Any concepts, procedures, reference info we could add.
    validations:
      required: true
  - type: textarea
    attributes:
      label: References
      description: Where did this first appear (if known) and has any other issues been opened related to this?
      value: |
        Related Pull Request(s):
        Related issue(s):
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description:
        The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/Eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md)
          required: true
