###
 # @format
 # -----
 # Project: @eventiva/eventiva
 # File: fix.yml
 # Path: \.github\ISSUE_TEMPLATE\fix.yml
 # Created Date: Monday, April 17th 2023
 # Author: Jonathan Stevens (Email: jonathan@Eventiva.co.uk, Github: https://github.com/TGTGamer)
 # -----
 # Contributing: Please read through our contributing guidelines. Included are directions for opening
 # issues, coding standards, and notes on development. These can be found at https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
 # 
 # Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
 # welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
 # -----
 # Copyright (c) 2023 Eventiva - All Rights Reserved
 # LICENSE: Creative Commons Zero v1.0 Universal (CC0-1.0)
 # -----
 # This program has been provided under confidence of the copyright holder and is 
 # licensed for copying, distribution and modification under the terms of
 # the Creative Commons Zero v1.0 Universal (CC0-1.0) published as the License,
 # or (at your option) any later version of this license.
 # 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # Creative Commons Zero v1.0 Universal for more details.
 # 
 # You should have received a copy of the Creative Commons Zero v1.0 Universal
 # along with this program. If not, please write to: jonathan@Eventiva.co.uk,
 # or see https://creativecommons.org/publicdomain/zero/1.0/legalcode
 # 
 # DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
 # -----
 # Last Modified: 08-05-2023
 # By: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
 # Current Version: 0.0.0
 ###


name: Code fix
description: Let us know about a solution to an existing issue
title: "fix([context]): "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this fix suggestion, we greatly appriciate it!
  - type: markdown
    attributes: 
      value: |
        Please use [context] in title to describe the part of the mono-repo is related to this issue.
        Context example: docs(components): {your title here}
        Valid options are: 
          - directory: The frontend website which displays our directory systems
          - proxy: The api endpoint for proxied connections to private ERP instances
          - image: The build image used when creating private ERP instances 
          - terraform: The definition of our build processes
          - ci/cd: The automations which run at issue create, pull request or push
          - cli: The custom rush based cli, used to streamline development processes
          - erp: The default module within our ERP instances
          - frappe: The frappe ecosystem which our erp instances are built on
          - payments: The payments module within our ERP instances
          - tours: The tours module within our ERP instances
          - logistics: The logistics module within our ERP instances
          - banking: The banking module within our ERP instances
          - tickets: The tickets module within our ERP instances
          - marketing: The marketing module within our ERP instances
          - hospitality: The hospitality module within our ERP instances
  - type: dropdown
    attributes:
      label: Features
      description: What product or feature(s) affected?
      multiple: true
      options:
        - "directory"
        - "proxy"
        - "image"
        - "terraform"
        - "ci/cd"
        - "cli"
        - "erp"
        - "frappe"
        - "payments"
        - "tours"
        - "logistics"
        - "banking"
        - "tickets"
        - "marketing"
        - "hospitality"
    validations:
      required: true
  - type: input
    attributes:
      label: Addresses issue
      value: "#{number}"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Console Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell

  - type: input
    attributes:
      label: Platform
      description: e.g. macOS, Google Cloud, ubuntu 18.04
    validations:
      required: true
  - type: input
    attributes:
      label: Browser
      description: e.g. Safari, chrome, edge, firefox
  - type: input
    attributes:
      label: Node Version
      description: e.g. v16.8.0
  - type: input
    attributes:
      label: Yarn Version
      description: e.g. v1.22.4
  - type: input
    attributes:
      label: Docker Version
      description: e.g. 19.03.12, build 48a66213fe

  - type: markdown
    attributes:
      value: |
        Please be honest here, we don't mind if you haven't done all these steps; 
        however, we need to know where has been tested and how extensively we need to test it ourselves.

        We would appreciate it if you could maintain this section cleanly and clearly. 
        If someone confirms your fix, add them to the "Fix confirmed by" section. 

        Our bot will automatically detect users in this section and ask them to submit a review.
  - type: checkboxes
    attributes:
      label: Fix Checklist
      options:
        - label: I have fixed on a clean installation
          required: false
        - label: I have fixed on a stable build
          required: false
        - label: I have fixed on a development build
          required: false
        - label: I have included logs or screenshots
          required: false
        - label: I have linked any related issues
          required: false
  - type: input
    attributes:
      label: Fix Confirmed by
      value: "- [ ] Fix confirmed by <!--@yourusername & @friendsusername-->"
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description:
        The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/Eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md)
          required: true
