###
 # @format
 # -----
 # Project: @resnovas/eventiva
 # File: maintenance.yml
 # Path: \.github\ISSUE_TEMPLATE\maintenance.yml
 # Created Date: Monday, April 17th 2023
 # Author: Jonathan Stevens (Email: jonathan@resnovas.com, Github: https://github.com/TGTGamer)
 # -----
 # Contributing: Please read through our contributing guidelines. Included are directions for opening
 # issues, coding standards, and notes on development. These can be found at https://github.com/resnovas/eventiva/blob/develop/CONTRIBUTING.md
 # 
 # Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
 # welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/resnovas/eventiva/blob/develop/CODE_OF_CONDUCT.md
 # -----
 # Copyright (c) 2023 Resnovas - All Rights Reserved
 # LICENSE: Creative Commons Zero v1.0 Universal (CC0-1.0)
 # -----
 # This program has been provided under confidence of the copyright holder and is 
 # licensed for copying, distribution and modification under the terms of
 # the Creative Commons Zero v1.0 Universal (CC0-1.0) published as the License,
 # or (at your option) any later version of this license.
 # 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # Creative Commons Zero v1.0 Universal for more details.
 # 
 # You should have received a copy of the Creative Commons Zero v1.0 Universal
 # along with this program. If not, please write to: jonathan@resnovas.com,
 # or see https://creativecommons.org/publicdomain/zero/1.0/legalcode
 # 
 # DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
 # -----
 # Last Modified: 01-05-2023
 # By: Jonathan Stevens (Email: jonathan@resnovas.com, Github: https://github.com/TGTGamer)
 # Current Version: 0.0.0
 ###


name: Code maintenance
description: Requesting Styling, Refactoring, Optimisation, Revert, Deprecated or Removal of an existing feature
title: "maintenance([context]): "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this maintenance request, we greatly appriciate it! 
  - type: markdown
    attributes:
      value: |
        Please use [context] in title to describe the part of the mono-repo is related to this issue.
        Context example: docs(components): {your title here}
        Valid options are: 
          - directory: The frontend website which displays our directory systems
          - proxy: The api endpoint for proxied connections to private ERP instances
          - image: The build image used when creating private ERP instances 
          - terraform: The definition of our build processes
          - ci/cd: The automations which run at issue create, pull request or push
          - cli: The custom rush based cli, used to streamline development processes
          - erp: The default module within our ERP instances
          - frappe: The frappe ecosystem which our erp instances are built on
          - payments: The payments module within our ERP instances
          - tours: The tours module within our ERP instances
          - logistics: The logistics module within our ERP instances
          - banking: The banking module within our ERP instances
          - tickets: The tickets module within our ERP instances
          - marketing: The marketing module within our ERP instances
          - hospitality: The hospitality module within our ERP instances
  - type: dropdown
    attributes:
      label: Features
      description: What product or feature(s) affected?
      multiple: true
      options:
        - "directory"
        - "proxy"
        - "image"
        - "terraform"
        - "ci/cd"
        - "cli"
        - "erp"
        - "frappe"
        - "payments"
        - "tours"
        - "logistics"
        - "banking"
        - "tickets"
        - "marketing"
        - "hospitality"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Type
      description: What type of maintenance is required?
      multiple: false
      options:
        - Style
        - Refactoring
        - Optimisation
        - Revert
        - Deprecated
        - Removal
    validations:
      required: true
  - type: input
    attributes:
      label: Assignee
      description: Who would you suggest does this? We suggest using blame to see who was the last to update the section. If unsure leave blank
    validations:
      required: false
  - type: input
    attributes:
      label: Risk
      description: "The risk associated with this change based on reliance of other features: Low, Medium, High. If unsure leave blank"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Maintenance Required
      description: A clear and concise description of what maintenance is required.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code snippet
      description: Please copy and paste any relevant code (if less than 5 lines). This will be automatically formatted into code, so no need for backticks.
      render: TypeScript
  - type: input
    attributes:
      label: Code snippet (link)
      description: "If the code is more than 5 lines and under 50 lines, include the code snippet link"
      placeholder: https://github.com/resnovas/eventiva/blob/develop/package.json#L1-L5
  - type: textarea
    attributes:
      label: Improvements
      description: |
        Explain the benefits of this maintenance.

        Transparent changes have the reasons for the change laid out clearly along with the change itself. This leads to fewer questions later on because people already have some understanding. A change with no public explanation can lead to a lot of extra rounds of questioning, which is less efficient. Avoid using terms such as "industry standard" or "best practices" as they are vague, opaque, and don't provide enough context as a reason for a change.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected risks
      description: |
        Please list features that can break because of this maintenance and how you intend to solve that.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Involved components
      description: |
        List files or directories that will be changed by the maintenance.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description:
        The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/Resnovas/eventiva/blob/develop/CODE_OF_CONDUCT.md)
          required: true
