name: Change Report
description: GitHub Action to generate a report from the recent code changes and post it to Slack or Discord
author: Max Prilutskiy
branding:
  icon: 'align-left'
  color: 'blue'
inputs:
  destination:
    required: true
    description: 'destination to post the report to'
  days: # change this
    required: true
    description: 'number of days to include into the report'
    default: 7
  channel:
    required: true
    description: 'channel to report'
    default: 'general'
runs:
  using: 'node16'
  main: 'dist/index.js'
