name: Change Report
description: GitHub Action to generate a report from the recent code changes and post it to Slack
author: Max Prilutskiy
inputs:
  days: # change this
    required: true
    description: 'number of days to include into the report'
    default: 7
  channel:
    required: true
    description: 'channel to report'
    default: 'general'
runs:
  using: 'node16'
  main: 'dist/index.js'
