###
# @format
# -----
# Project: @eventiva/eventiva
# File: compose.eventiva.yaml
# Path: \.devcontainer\compose.eventiva.yaml
# Created Date: Wednesday, October 18th 2023
# Author: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
# -----
# Contributing: Please read through our contributing guidelines. Included are directions for opening
# issues, coding standards, and notes on development. These can be found at https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
#
# Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
# welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
# -----
# Copyright (c) 2023 Eventiva - All Rights Reserved
# LICENSE: Creative Commons Zero v1.0 Universal (CC0-1.0)
# -----
# This program has been provided under confidence of the copyright holder and is
# licensed for copying, distribution and modification under the terms of
# the Creative Commons Zero v1.0 Universal (CC0-1.0) published as the License,
# or (at your option) any later version of this license.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Creative Commons Zero v1.0 Universal for more details.
#
# You should have received a copy of the Creative Commons Zero v1.0 Universal
# along with this program. If not, please write to: jonathan.stevens@eventiva.co.uk,
# or see https://creativecommons.org/publicdomain/zero/1.0/legalcode
#
# DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
# -----
# Last Modified: 24-11-2023
# By: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
# Current Version: 0.0.0
###

services:
  backend:
    build:
      context: ./
      dockerfile: dockerfile
      args:
        ERPNEXT_VERSION: ${ERPNEXT_VERSION:?No ERPNext version set}
    volumes:
      # bind the workspace to /home/frappe/frappe-bench/workspace
      - ../:/home/frappe/frappe-bench/workspace
      # - ../projects/modules/eventiva_core:/home/frappe/frappe-bench/apps/eventiva_core
      # - ../projects/modules/vetting:/home/frappe/frappe-bench/apps/vetting
      # - ../projects/modules/fleet_management:/home/frappe/frappe-bench/apps/fleet_management
      # - ../projects/modules/gaming:/home/frappe/frappe-bench/apps/gaming
      # - ../projects/modules/custody:/home/frappe/frappe-bench/apps/custody
      # - ../projects/modules/justice:/home/frappe/frappe-bench/apps/justice
      # - ../projects/modules/incident_management:/home/frappe/frappe-bench/apps/incident_management
      # - ../projects/modules/teamspeak_integration:/home/frappe/frappe-bench/apps/teamspeak_integration
      # - ../projects/modules/discord_integration:/home/frappe/frappe-bench/apps/discord_integration
      # - ../projects/modules/control_centre:/home/frappe/frappe-bench/apps/control_centre
      # - ../projects/modules/grand_theft_auto:/home/frappe/frappe-bench/apps/grand_theft_auto
      # - ../projects/modules/segment_connect:/home/frappe/frappe-bench/apps/segment_connect
      # copy ssh keys to /home/frappe/.ssh
      - ~/.ssh:/home/frappe/.ssh
      # copy gpg keys to /home/frappe/.gnupg
      - ~/.gnupg:/home/frappe/.gnupg
  
  # discord:
  #   build:
  #     context: ./
  #     dockerfile: dockerfile
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     # bind the workspace
  #     - ../../:/workspace
  #   # command: >
  #   #   sh -c "
  #   #     bit install &&
  #   #     bit app run helper
  #   #   "
