###
# @format
# -----
# Project: @eventiva/eventiva
# File: dockerfile
# Path: \.devcontainer\dockerfile
# Created Date: Sunday, January 14th 2024
# Author: Jonathan Stevens, jonathan@resnovas.com
# Github: https://github.com/TGTGamer
# -----
# Contributing: Please read through our contributing guidelines.
# Included are directions for opening issues, coding standards,
# and notes on development. These can be found at
# https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
# -----
# Code of Conduct: This project abides by the Contributor Covenant, v2.0
# Please interact in ways that contribute to an open, welcoming, diverse,
# inclusive, and healthy community. Our Code of Conduct can be found at
# https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
# -----
# Copyright (c) 2024 Resnovas - All Rights Reserved
# LICENSE: GNU General Public License v2.0 or later (GPL-2.0-or-later)
# -----
# This program has been provided under confidence of the copyright holder and
# is licensed for copying, distribution and modification under the terms of
# the GNU General Public License v2.0 or later (GPL-2.0-or-later) published as the License,
# or (at your option) any later version of this license.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License v2.0 or later for more details.
# You should have received a copy of the GNU General Public License v2.0 or later
# along with this program. If not, please write to: jonathan@resnovas.com,
# or see https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
# -----
# This project abides by the GPL Cooperation Commitment.
# Before filing or continuing to prosecute any legal proceeding or claim
# (other than a Defensive Action) arising from termination of a Covered
# License, we commit to extend to the person or entity ('you') accused
# of violating the Covered License the following provisions regarding
# cure and reinstatement, taken from GPL version 3.
# For further details on the GPL Cooperation Commitment please visit
# the official website: https://gplcc.github.io/gplcc/
# -----
# DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE
###



 # Use the frappe/erpnext image with a customisable version using a passed in argument from the compose file
ARG ERPNEXT_VERSION
FROM frappe/erpnext:${ERPNEXT_VERSION}


USER frappe
WORKDIR /home/frappe/frappe-bench/
# check to see if the lms folder already exists and if it doesn't then clone the repo
RUN if [ ! -d "/home/frappe/frappe-bench/apps/lms" ] ; then bench get-app https://github.com/frappe/lms.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/lending" ] ; then bench get-app https://github.com/frappe/lending.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/healthcare" ] ; then bench get-app https://github.com/frappe/health.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/payments" ] ; then bench get-app https://github.com/frappe/payments.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/webshop" ] ; then bench get-app https://github.com/frappe/webshop.git ; fi
RUN if [ ! -d "/home/frappe/frappe-bench/apps/it_management" ] ; then bench get-app https://github.com/phamos-eu/it_management.git ; fi

# RUN bench install-app erpnext
# RUN bench install-app hrms
# RUN bench install-app it_management
# RUN bench install-app lending
# RUN bench install-app payments
# RUN bench install-app webshop
# RUN bench install-app lms
# RUN bench install-app healthcare

# installl bit via bvm using npx @teambit/bvm install
RUN npx @teambit/bvm install

# This line of code installs the 'opencommit' package globally via npm. This package is necessary for version control and collaboration with commit-specific feedback.
RUN npm install -g opencommit