name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/cache@v2
        with:
          path: |
            **/*
          key: ${{ runner.os }}-checkout-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-checkout-
      - uses: actions/checkout@v2
    - if: startsWith(matrix.os, 'macos')
      run: brew install bash
    - run:
        git config --global user.email "you@example.com";
        git config --global user.name "Your Name";
    - run: make test
