###
# @format
# -----
# Project: @eventiva/eventiva
# File: config.yml
# Path: \projects\workflows\.github\.github\ISSUE_TEMPLATE\config.yml
# Created Date: Sunday, January 14th 2024
# Author: Jonathan Stevens, jonathan@resnovas.com
# Github: https://github.com/TGTGamer
# -----
# Contributing: Please read through our contributing guidelines.
# Included are directions for opening issues, coding standards,
# and notes on development. These can be found at
# https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
# -----
# Code of Conduct: This project abides by the Contributor Covenant, v2.0
# Please interact in ways that contribute to an open, welcoming, diverse,
# inclusive, and healthy community. Our Code of Conduct can be found at
# https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
# -----
# Copyright (c) 2024 Resnovas - All Rights Reserved
# LICENSE: GNU General Public License v2.0 or later (GPL-2.0-or-later)
# -----
# This program has been provided under confidence of the copyright holder and
# is licensed for copying, distribution and modification under the terms
# of the GNU General Public License v2.0 or later (GPL-2.0-or-later) published as the License,
# or (at your option) any later version of this license.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License v2.0 or later for more details.
# You should have received a copy of the GNU General Public License v2.0 or later
# along with this program. If not, please write to: jonathan@resnovas.com,
# or see https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
# -----
# This project abides by the GPL Cooperation Commitment.
# Before filing or continuing to prosecute any legal proceeding or claim
# (other than a Defensive Action) arising from termination of a Covered
# License, we commit to extend to the person or entity ('you') accused
# of violating the Covered License the following provisions regarding
# cure and reinstatement, taken from GPL version 3.
# For further details on the GPL Cooperation Commitment please visit
# the official website: https://gplcc.github.io/gplcc/
# -----
# DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE
###



blank_issues_enabled: false

contact_links:    
  - name: Questions & Answers via Discord
    url: https://www.answeroverflow.com/c/352754251434426368
    about: Join the public discord to get help with your issue

  - name: Technical Support
    url: https://eventivaltd.atlassian.net/servicedesk/customer/portal/3/group/11/create/33
    about: Need help installing, configuring, or troublesnooting? Select this to request assistance.

  - name: Report a bug
    url: https://eventivaltd.atlassian.net/servicedesk/customer/portal/3/group/11/create/38
    about: Tell us the problems you're experiencing-

  - name: Request Features
    url: https://eventivaltd.atlassian.net/servicedesk/customer/portal/3/group/11/create/39
    about: Suggest a new feature for our project
  
  - name: Suggest Improvements
    url: https://eventivaltd.atlassian.net/servicedesk/customer/portal/3/group/11/create/40
    about: See a place where we can do better? We're all ears.

  - name: Maintenance Request
    url: https://eventivaltd.atlassian.net/servicedesk/customer/portal/3/group/11/create/41
    about: Found something that needs a bit of love? Let us know that we should review the Documentation, Styling, Refactoring, Optimisation, Deprecated or Removal of an existing feature.

  - name: Code Discussion
    url: https://github.com/Eventiva/eventiva/discussions/new
    about: Start a discussion about our project's development

  - name: Contributor Code of Conduct
    url: https://github.com/Eventiva/contributors/blob/main/CODE_OF_CONDUCT.md
    about: Showcase yourself
