blank_issues_enabled: false

contact_links:
  - name: Questions & Answers via Discord
    url: https://www.answeroverflow.com/c/352754251434426368
    about: Join the public discord to get help with your issue

  - name: Technical Support
    url: https://eventivaltd.atlassian.net/servicedesk/customer/portal/3/group/11/create/33
    about: Need help installing, configuring, or troublesnooting? Select this to request assistance.

  - name: Report a bug
    url: https://eventivaltd.atlassian.net/servicedesk/customer/portal/3/group/11/create/38
    about: Tell us the problems you're experiencing-

  - name: Request Features
    url: https://eventivaltd.atlassian.net/servicedesk/customer/portal/3/group/11/create/39
    about: Suggest a new feature for our project

  - name: Suggest Improvements
    url: https://eventivaltd.atlassian.net/servicedesk/customer/portal/3/group/11/create/40
    about: See a place where we can do better? We're all ears.

  - name: Maintenance Request
    url: https://eventivaltd.atlassian.net/servicedesk/customer/portal/3/group/11/create/41
    about: Found something that needs a bit of love? Let us know that we should review the Documentation, Styling, Refactoring, Optimisation, Deprecated or Removal of an existing feature.

  - name: Code Discussion
    url: https://github.com/Eventiva/eventiva/discussions/new
    about: Start a discussion about our project's development

  - name: Contributor Code of Conduct
    url: https://github.com/Eventiva/contributors/blob/main/CODE_OF_CONDUCT.md
    about: Showcase yourself
