###
 # @format
 # -----
 # Project: @eventiva/eventiva
 # File: compose.multi-bench-ssl.yaml
 # Path: \.devcontainer\overrides\compose.multi-bench-ssl.yaml
 # Created Date: Sunday, January 14th 2024
 # Author: Jonathan Stevens (Email: jonathan@resnovas.com, Github: https://github.com/TGTGamer)
 # -----
 # Contributing: Please read through our contributing guidelines. Included are directions for opening
 # issues, coding standards, and notes on development. These can be found at https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
 # 
 # Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
 # welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
 # -----
 # Copyright (c) 2024 Resnovas - All Rights Reserved
 # LICENSE: Creative Commons Zero v1.0 Universal (CC0-1.0)
 # -----
 # This program has been provided under confidence of the copyright holder and is 
 # licensed for copying, distribution and modification under the terms of
 # the Creative Commons Zero v1.0 Universal (CC0-1.0) published as the License,
 # or (at your option) any later version of this license.
 # 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # Creative Commons Zero v1.0 Universal for more details.
 # 
 # You should have received a copy of the Creative Commons Zero v1.0 Universal
 # along with this program. If not, please write to: jonathan@resnovas.com,
 # or see https://creativecommons.org/publicdomain/zero/1.0/legalcode
 # 
 # DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
 ###

services: 
  frontend:
    labels:
      # ${ROUTER}-http to use the middleware to redirect to https
      - traefik.http.routers.${ROUTER}-http.middlewares=https-redirect
      # ${ROUTER}-https the actual router using HTTPS
      # Uses the environment variable SITES
      - traefik.http.routers.${ROUTER}-https.rule=Host(${SITES?SITES not set})
      - traefik.http.routers.${ROUTER}-https.entrypoints=https
      - traefik.http.routers.${ROUTER}-https.tls=true
      # Use the service ${ROUTER} with the frontend
      - traefik.http.routers.${ROUTER}-https.service=${ROUTER}
      # Use the "le" (Let's Encrypt) resolver created below
      - traefik.http.routers.${ROUTER}-https.tls.certresolver=le
