###
# @format
# -----
# Project: @eventiva/eventiva
# File: branch-lane.yml
# Path: \.github\workflows\branch-lane.yml
# Created Date: Thursday, December 7th 2023
# Author: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
# -----
# Contributing: Please read through our contributing guidelines. Included are directions for opening
# issues, coding standards, and notes on development. These can be found at https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
#
# Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
# welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
# -----
# Copyright (c) 2023 Eventiva - All Rights Reserved
# LICENSE: Creative Commons Zero v1.0 Universal (CC0-1.0)
# -----
# This program has been provided under confidence of the copyright holder and is
# licensed for copying, distribution and modification under the terms of
# the Creative Commons Zero v1.0 Universal (CC0-1.0) published as the License,
# or (at your option) any later version of this license.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Creative Commons Zero v1.0 Universal for more details.
#
# You should have received a copy of the Creative Commons Zero v1.0 Universal
# along with this program. If not, please write to: jonathan.stevens@eventiva.co.uk,
# or see https://creativecommons.org/publicdomain/zero/1.0/legalcode
#
# DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
# -----
# Last Modified: 07-12-2023
# By: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
# Current Version: 0.0.0
###

name: Components - Bit Branch Lane
on:
  push:
    branches-ignore:
      - main # or your default branch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@6705383eabd01833acfe8412ec697384830e1455 # v1.8.7
        with: 
          github_token: ${{ secrets.BOT_TOKEN }}
          comment_on_pr: false
          theme: dark
          proc_trace_sys_enable: true
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Initialize Bit
        uses: bit-tasks/init@e2ce273c218d39dfc68925c80f6da33e16407c87 # v1
      - name: Resolve component packages from bit.cloud registry (Mandatory for component installation using package managers other than Bit)
        run: |
          npm config set '@bit:registry' https://node-registry.bit.cloud
          npm config set '@teambit:registry' https://node-registry.bit.cloud
          npm config set '@eventiva:registry' https://node-registry.bit.cloud
          npm config set //node-registry.bit.cloud/:_authToken ${{ env.BIT_CONFIG_USER_TOKEN }}
      - name: Bit Branch Lane
        uses: bit-tasks/branch-lane@32db30e0a8470983b15f86e06012b8d76e1820c0 # v1
      - name: Commit Bitmap
        uses: bit-tasks/commit-bitmap@c31e1ab8acfc20dd150a55b1aae894e49460aecc # v1
