name: Chore - Generate Animation

on:
    schedule:
        - cron: '0 0 * * *'

    # allows to manually run the job at any time
    workflow_dispatch:

    # run on every push on the master branch
    push:
        branches:
            - release-please*

permissions:
    contents: read

jobs:
    generate:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - uses: ./.github/actions/security-preamble

            - uses: ./.github/actions/checkout-repo
              with:
                  token: ${{ secrets.BOT_TOKEN || github.token }}
                  submodules: 'recursive'

            - uses: ./.github/actions/git-ssh-setup
              with:
                  ssh-key: ${{ secrets.BOT_GIT_SSH_KEY }}
                  user-name: ${{ secrets.GIT_USER_NAME }}
                  user-email: ${{ secrets.GIT_USER_EMAIL }}

            # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
            - name: generate github-contribution-grid-snake.svg
              uses: Platane/snk/svg-only@v3.4.1 # v3.2.0
              with:
                  github_user_name: EventivaLtd
                  outputs: |
                      .github/images/github-snake.svg
                      .github/images/github-snake-dark.svg?palette=github-dark
            - name: Commit files
              uses: EndBug/add-and-commit@v9.1.4 # v7.5.0
              with:
                  add: '.github/images/'
                  push: true
