name: Chore - Generate Animation

on:
  schedule:
    - cron: "0 0 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
      - release-please*

permissions:
  contents: read

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.6.1 # v2.6.1
        with:
          egress-policy: audit

      - name: Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0 # v1.8.7
        with:
          github_token: ${{ secrets.BOT_TOKEN || github.token }}
          comment_on_pr: false
          theme: dark
          proc_trace_sys_enable: true

      # checks out the repository
      - uses: actions/checkout@v4.1.6
        with:
          submodules: 'recursive'
          token: "${{ secrets.BOT_TOKEN || github.token }}"

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.BOT_GIT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # ensure git is using the ssh key
      - name: Ensure git is using the SSH key
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-add -l | grep -q "$(ssh-keygen -lf ~/.ssh/id_rsa | awk '{print $2}')" || (echo "Failed to add SSH key" && exit 1)

      # setup git to use the ssh key
      - name: Setup git
        run: |
          git config --global user.name ${{secrets.GIT_USER_NAME}}
          git config --global user.email ${{secrets.GIT_USER_EMAIL}}
          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/id_rsa
          git config --global commit.gpgsign true
          git config --global tag.gpgsign true

      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3.2.0 # v3.2.0
        with:
          github_user_name: EventivaLtd
          outputs: |
            .github/images/github-snake.svg
            .github/images/github-snake-dark.svg?palette=github-dark
      - name: Commit files
        uses: EndBug/add-and-commit@v9.1.4 # v7.5.0
        with:
          add: ".github/images/"
          push: true
