# Trunk code quality checks - https://docs.trunk.io/code-quality/ci-setup
name: CI - Trunk
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  trunk:
    name: Trunk check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Trunk check
        uses: trunk-io/trunk-action@v1
        env:
          TRUNK_ORG_URL_SLUG: ${{ secrets.TRUNK_ORG_URL_SLUG }}
          TRUNK_API_TOKEN: ${{ secrets.TRUNK_API_TOKEN }}
