name: Management - Github Management
on:
  issues:
    types: [ opened, edited, closed, reopened ]
  pull_request:
    types: [ opened, edited, closed, reopened, synchronize ]
  merge_group:

permissions:
  contents: read

jobs:
  release-mastermind:
    name: Release Mastermind
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.6.1 # v2.6.1
        with:
          egress-policy: audit

      - name: Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0 # v1.8.7
        with:
          github_token: ${{ secrets.BOT_TOKEN || github.token }}
          comment_on_pr: false
          theme: dark
          proc_trace_sys_enable: true

      - name: Release Mastermind
        uses: Resnovas/smartcloud # 1.0.0-beta.8
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN || github.token }}
          config: .github/config.json
          configRef: main
