name: Management - Contributor License Agreement Management
on:
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened, closed, synchronize ]

permissions:
  actions: read
  contents: read
  pull-requests: read
  statuses: read

# Ensures the CLA is signed
jobs:
  CLAssistant:
    name: "CLA Assistant"
    permissions:
      actions: write
      contents: write
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest
    if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || github.event_name == 'pull_request_target' )
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.6.1 # v2.6.1
        with:
          egress-policy: audit

      - name: Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0 # v1.8.7
        with:
          github_token: ${{ secrets.BOT_TOKEN || github.token }}
          comment_on_pr: false
          theme: dark
          proc_trace_sys_enable: true

      - name: CLA Assistant
        uses: cla-assistant/github-action@v2.3.2 # v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN || github.token }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.BOT_TOKEN || github.token }}
        with:
          path-to-signatures: "contributors.json"
          path-to-document: "https://github.com/Eventiva/.github?tab=coc-ov-file"
          allowlist: ResnovasLtd, EventivaLtd, dependabot, dependabot[bot], bot*, restyled-io, atlassian-compass[bot], TMateSoft, restyled-io[bot], trunk-io[bot], trunk-io, sweep-ai[bot], sweep-ai, restyled-commits, restyled-commits[bot], step-security-bot
          branch: "main"
          remote-organization-name: "Eventiva"
          remote-repository-name: ".github"
