###
# @format
# -----
# Project: @eventiva/eventiva
# File: management-discord_changelog.yml
# Path: \.github\workflows\management-discord_changelog.yml
# Created Date: Monday, December 4th 2023
# Author: Jonathan Stevens (Email: jonathan@resnovas.com
# -----
# Contributing: Please read through our contributing guidelines. Included are directions for opening
# issues, coding standards, and notes on development. These can be found at https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
#
# Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
# welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
# -----
# Copyright (c) 2024 Resnovas - All Rights Reserved
# LICENSE: Creative Commons Zero v1.0 Universal (CC0-1.0)
# -----
# This program has been provided under confidence of the copyright holder and is
# licensed for copying, distribution and modification under the terms of
# the Creative Commons Zero v1.0 Universal (CC0-1.0) published as the License,
# or (at your option) any later version of this license.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Creative Commons Zero v1.0 Universal for more details.
#
# You should have received a copy of the Creative Commons Zero v1.0 Universal
# along with this program. If not, please write to: jonathan@resnovas.com,
# or see https://creativecommons.org/publicdomain/zero/1.0/legalcode
#
# DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
# -----
# Last Modified: Thu Jan 25 2024
# By: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
# Current Version: 0.0.0
###

name: Management - Change Report
on:
  workflow_dispatch:
  schedule:
    - cron: '0 01 * * 1/2'

permissions:
  contents: read

jobs:
  change-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@6705383eabd01833acfe8412ec697384830e1455 # v1.8.7
        with: 
          github_token: ${{ secrets.BOT_TOKEN }}
          comment_on_pr: false
          theme: dark
          proc_trace_sys_enable: true
          
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          # Use a large enough fetch depth to ensure the action can find the commit history to work with
          fetch-depth: 250

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          # The destination to post the report to.
          # "slack" and "discord" are supported
          destination: 'discord'
          # Number of days to include into the report
          days: 2
          # Slack channel to post the report to.
          # For Slack it's the name of the channel, without the leading "#",
          # For Discord it's the channel ID
          channel: '1175861376711925762'
        env:
          # Your OpenAI API key, used to generate the report
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Your Slack bot token, used to post the report on behalf of the bot.
          # Only needed if you're posting to Slack
          # SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          # Your Slack signing secret, used to verify the request is coming from Slack
          # Only needed if you're posting to Slack
          # SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          # Your Discord bot token, used to post the report on behalf of the bot.
          # Only needed if you're posting to Discord
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: ${{ github.repository }}

  frappe-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 250
          repository: 'frappe/frappe'

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          destination: 'discord'
          days: 2
          channel: '1181650952831385641, 1175861376711925762'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: Frappe Framework

  human-resources-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 250
          repository: 'frappe/hrms'

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          destination: 'discord'
          days: 2
          channel: '1183092847231119570, 1175861376711925762'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: Human Resources

  erp-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 250
          repository: 'frappe/erpnext'

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          destination: 'discord'
          days: 2
          channel: '1181651008410095617, 1175861376711925762'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: Enterprise Resource Planning

  learning-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 250
          repository: 'frappe/lms'

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          destination: 'discord'
          days: 2
          channel: '1181651075158253728, 1175861376711925762'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: Learning Management System

  lending-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 250
          repository: 'frappe/lending'

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          destination: 'discord'
          days: 2
          channel: '1181651400955023360, 1175861376711925762'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: Lending

  healthcare-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 250
          repository: 'frappe/health'

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          destination: 'discord'
          days: 2
          channel: '1181651559214485556, 1175861376711925762'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: Heathcare Management System

  payments-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 250
          repository: 'frappe/health'

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          destination: 'discord'
          days: 2
          channel: '1181651624893104188, 1175861376711925762'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: Payment Management System

  webshop-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 250
          repository: 'frappe/health'

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          destination: 'discord'
          days: 2
          channel: '1181651810570743878, 1175861376711925762'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: Webshop Management System

  it_management-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 250
          repository: 'phamos-eu/it_management'

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          destination: 'discord'
          days: 2
          channel: '1181652191023484938, 1175861376711925762'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: IT Management System

  website-builder-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 250
          repository: 'frappe/builder'

      - uses: eventiva/change-report@356931c8a20afa16664e3dcfc4567ed924a34a43 # main
        with:
          destination: 'discord'
          days: 2
          channel: '1181657346812940328, 1175861376711925762'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GITHUB_REPO_NAME: Website Builder System
