name: Security - GitGuardian scan

on:
    merge_group:
    push:
        branches:
            - main
            - develop
            - release/*
    pull_request:
        branches:
            - main
            - develop
            - release/*

permissions:
    contents: read

jobs:
    scanning:
        name: GitGuardian scan
        runs-on: ubuntu-latest
        env:
            BOT_GIT_SSH_KEY: ${{ secrets.BOT_GIT_SSH_KEY }}
            GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
            GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        steps:
            - uses: actions/checkout@v6
              with:
                  token: ${{ secrets.BOT_TOKEN || github.token }}
                  submodules: 'recursive'

            - name: Harden Runner
              uses: step-security/harden-runner@v2.15.1
              with:
                  egress-policy: audit

            - uses: ./.github/actions/git-ssh-setup
              if: env.BOT_GIT_SSH_KEY != '' && env.GIT_USER_NAME != '' && env.GIT_USER_EMAIL != ''
              with:
                  ssh-key: ${{ secrets.BOT_GIT_SSH_KEY }}
                  user-name: ${{ secrets.GIT_USER_NAME }}
                  user-email: ${{ secrets.GIT_USER_EMAIL }}

            - name: GitGuardian scan
              if: env.GITGUARDIAN_API_KEY != ''
              uses: GitGuardian/ggshield-action@v1.49.0
              env:
                  GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
                  GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
                  GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
                  GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
                  GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
                  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN || github.token }}
