name: Security - GitGuardian iac scan
on:
    push:
        paths:
            - '.terraform/**'
    pull_request:
        paths:
            - '.terraform/**'

permissions:
    contents: read

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    scanning:
        name: GitGuardian iac scan
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/security-preamble

            - uses: ./.github/actions/checkout-repo
              with:
                  token: ${{ secrets.BOT_TOKEN || github.token }}
                  submodules: 'recursive'

            - uses: ./.github/actions/git-ssh-setup
              with:
                  ssh-key: ${{ secrets.BOT_GIT_SSH_KEY }}
                  user-name: ${{ secrets.GIT_USER_NAME }}
                  user-email: ${{ secrets.GIT_USER_EMAIL }}

            - name: Setup NPM Registry
              run: |
                  npm config set '@bit:registry' https://node-registry.bit.cloud
                  npm config set '@teambit:registry' https://node-registry.bit.cloud
                  npm config set '@eventiva:registry' https://node-registry.bit.cloud
                  npm config set //node-registry.bit.cloud/:_authToken ${{ secrets.BIT_CONFIG_USER_TOKEN }}

            - name: GitGuardian iac scan
              uses: GitGuardian/ggshield/actions/iac@v1 # main
              with:
                  args: ./terraform/ --minimum-severity CRITICAL # pass arguments to the action. If missing, will scan the current directory
              env:
                  GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
