###
 # @format
 # -----
 # Project: @eventiva/eventiva
 # File: subrepo.yml
 # Path: \.github\workflows\subrepo.yml
 # Created Date: Wednesday, December 20th 2023
 # Author: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
 # -----
 # Contributing: Please read through our contributing guidelines. Included are directions for opening
 # issues, coding standards, and notes on development. These can be found at https://github.com/eventiva/eventiva/blob/develop/CONTRIBUTING.md
 # 
 # Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
 # welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/eventiva/eventiva/blob/develop/CODE_OF_CONDUCT.md
 # -----
 # Copyright (c) 2023 Eventiva - All Rights Reserved
 # LICENSE: GNU General Public License v3.0 only (GPL-3.0)
 # -----
 # This program has been provided under confidence of the copyright holder and is 
 # licensed for copying, distribution and modification under the terms of
 # the GNU General Public License v3.0 only (GPL-3.0) published as the License,
 # or (at your option) any later version of this license.
 # 
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License v3.0 only for more details.
 # 
 # You should have received a copy of the GNU General Public License v3.0 only
 # along with this program. If not, please write to: jonathan.stevens@eventiva.co.uk,
 # or see https://www.gnu.org/licenses/gpl-3.0-standalone.html
 # 
 # DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
 ###

name: Chore - Subrepo

on:
  push:
    branches:
      - develop

jobs:
  subrepo:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        repository: 'ingydotnet/git-subrepo'
        path: 'git-subrepo'

    - name: Source git-subrepo
      run: source $GITHUB_WORKSPACE/git-subrepo/.rc

    - uses: actions/checkout@v3
      with:
        path: 'eventiva'

    - name: setup git configuration
      working-directory: eventiva
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    
    - name: Update subrepo
      working-directory: eventiva
      run: git subrepo push --all